# Site settings
title: Technically Shaun
email: me@technicallyshaun.com
description: >-
  A blog about technology, programming, and software development.
  Sharing insights, tutorials, and thoughts on the latest in tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://technicallyshaun.com" # the base hostname & protocol for your site
github_username:  technicallyshaun

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Minima theme settings
minima:
  date_format: "%B %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/technicallyshaun" }
    - { platform: youtube, user_url: "https://www.youtube.com/@TechnicallyShaun" }

# SEO settings
author:
  name: Shaun Smith

# Google Analytics (uncomment and add your tracking ID when ready)
google_analytics: G-DHQKSG0WCF

# Disqus Comments (uncomment and add your shortname when ready)
# disqus:
#   shortname: technicallyshaun

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CNAME

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Permalinks
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      share: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"